# Define a BACKEND variable usable in sub-Makefiles

PLATFORM := $(shell opam list --installed --short mirage-xen)
NET := $(shell opam list --installed --short mirage-net-socket)

ifeq ($(strip $(PLATFORM)),mirage-xen)
	BACKEND := --xen
else
	BACKEND := --unix
    ifeq ($(strip $(NET)),mirage-net-socket)
        BACKEND += --socket
    endif
endif
